language: node_js
node_js:
- '8'
script: yarn run deploy
deploy:
- provider: lambda
  access_key_id: AKIAJWUKJA7KSTTQTWCQ
  function_name: wedding-site
  role: arn:aws:iam::289214495984:role/service-role/wedding-site-role
  runtime: nodejs8.10
  handler_name: handler
  zip: ./lambda_deploy/lambda.zip
  timeout: 30
  memory: 256
  subnet_ids:
  - subnet-9624bcf3
  - subnet-71d89928
  security_group_ids:
  - sg-6f1ec008
  environment_variables:
  - secure: pyOki5GjvC0O0rrZcbkv7de9j/jZzhXAr/i0asG54+L8hGkhKiYEBbj7OwcevKijlqcGDIAUvYbt2KOGiZLdTfafUWxIxgPOm5WXSlJvzM38JJur/ubMZQ97QU4RRbklX5xL3zgU22cvTxqSxerySwmYjVJbpI2BRFba9PmHDHpTP7bfuAtgnOiasx5DT1zJfY0kB+XN03B0icfTIdiWKDpYC2t752T5hy43B8H9Uo8nUG1+Bbw9CIq7roq+ppodZwlLb6IsrXWT71w3hVaLHu5kGxxAljR/lB1ey14E/j2DLlrUPlAOw8ShwQbv83/E5aFxuWuDOjvVqCq2sEIIAAR5RX+3fE9nzpSjXB4OZQMz7S5xVL5gAySiRqoFh5vmGHBqYOWi3bfhlo7dFkTT6ztxKVtPqWuQw9LifuI1kQYyKsBFbu99h3L6a5u4+SH77u/w2rdZ/qlZmSOoHH+DdB2VpHtY+NrunN2Yl2s8n8xappoPH2idYXLGSaCKMKr3wBDwRSua1r7P2PQ02r5+3VsMo6yUKBdW8JmEAjL7eXc9eOU8fcwaPmv17Q8XDg6S8I58cBsiJaVqXOZmCZy2zYTyPQPNQ6LFT5cpYRrgOLlQPtSByx3zHCa1PwboeiiAjREyEP8fZ6uGl5gZ/FM8QEkCQ/OXwerPUs7GanFAgJQ=
  secret_access_key:
    secure: VyLtXc44aleTH2994Y10YEETYvtM56NGGORCQVLHBMwaIl8io1mY+rmHgRLfqq4GbdhgbzNPoOcu4w9tGu2uhEB7vkN4Y6cOHaZxQNcNfE5tuYdTaaytuMc5gWBgvlnPi9ujrqtLgw30VfKMVVUHH938xmZ5k8deg6wAaFlFwBV+lPPKXhxVBDzCVRkmlb5fIuWYUJCFCcUGVYDIr1Zmau9BOZ32SFtpEhAPXBY76MuGh73Qms6DsxLEcMiZjcA+5M0Zs4nCv+Ih+5b7Fn1Z5f1A15Q0V9GOGBwHjov609PpxAy4MTacBWefjCiE8a3pY5ECy1lZMzgWLuq6uEsPK769HWvjoTSrQiTQsQDFMFA+QM2WVOJcTJH3z901V/bQ790pQ7++CXwWyyI77Ck+tV004Inn3YeKWOuiGIKx+e+905Q39CUzuwk6DQhaN3Eq45pBdoJ+dEdEs6x+nhmKyz5v0pUku0sCnF49Qoseuy9k56A5AGENZlx0VW3HB7a76ro0bJD3J/kRTzBmwq4VzSuwJ67dnnAVE1k7k1Ah8ZKZa+aDd5B4i35mY/WLurzumPGW5JqHgwdgC6Cw+6gvp6I9hTRlJ5SjfZ+mLALsgoDuGyEazuPpeFb9WkcTass0UENLopDTVvr7qu3nmINzOq5THWukaen2lENL2cPA7C4=
- provider: s3
  access_key_id: AKIAJWUKJA7KSTTQTWCQ
  secret_access_key:
    secure: VyLtXc44aleTH2994Y10YEETYvtM56NGGORCQVLHBMwaIl8io1mY+rmHgRLfqq4GbdhgbzNPoOcu4w9tGu2uhEB7vkN4Y6cOHaZxQNcNfE5tuYdTaaytuMc5gWBgvlnPi9ujrqtLgw30VfKMVVUHH938xmZ5k8deg6wAaFlFwBV+lPPKXhxVBDzCVRkmlb5fIuWYUJCFCcUGVYDIr1Zmau9BOZ32SFtpEhAPXBY76MuGh73Qms6DsxLEcMiZjcA+5M0Zs4nCv+Ih+5b7Fn1Z5f1A15Q0V9GOGBwHjov609PpxAy4MTacBWefjCiE8a3pY5ECy1lZMzgWLuq6uEsPK769HWvjoTSrQiTQsQDFMFA+QM2WVOJcTJH3z901V/bQ790pQ7++CXwWyyI77Ck+tV004Inn3YeKWOuiGIKx+e+905Q39CUzuwk6DQhaN3Eq45pBdoJ+dEdEs6x+nhmKyz5v0pUku0sCnF49Qoseuy9k56A5AGENZlx0VW3HB7a76ro0bJD3J/kRTzBmwq4VzSuwJ67dnnAVE1k7k1Ah8ZKZa+aDd5B4i35mY/WLurzumPGW5JqHgwdgC6Cw+6gvp6I9hTRlJ5SjfZ+mLALsgoDuGyEazuPpeFb9WkcTass0UENLopDTVvr7qu3nmINzOq5THWukaen2lENL2cPA7C4=
  bucket: jake-chitel-wedding-site
  acl: public_read
  skip_cleanup: true
  local_dir: build
branches:
  only:
  - master