language: node_js
node_js:
- '8'
script: npm run deploy
deploy:
  provider: lambda
  access_key_id: AKIAJWUKJA7KSTTQTWCQ
  function_name: wedding-site
  role: arn:aws:iam::289214495984:role/service-role/wedding-site-role
  handler_name: index.handler
  zip: ./build/lambda.zip
  secret_access_key:
    secure: VyLtXc44aleTH2994Y10YEETYvtM56NGGORCQVLHBMwaIl8io1mY+rmHgRLfqq4GbdhgbzNPoOcu4w9tGu2uhEB7vkN4Y6cOHaZxQNcNfE5tuYdTaaytuMc5gWBgvlnPi9ujrqtLgw30VfKMVVUHH938xmZ5k8deg6wAaFlFwBV+lPPKXhxVBDzCVRkmlb5fIuWYUJCFCcUGVYDIr1Zmau9BOZ32SFtpEhAPXBY76MuGh73Qms6DsxLEcMiZjcA+5M0Zs4nCv+Ih+5b7Fn1Z5f1A15Q0V9GOGBwHjov609PpxAy4MTacBWefjCiE8a3pY5ECy1lZMzgWLuq6uEsPK769HWvjoTSrQiTQsQDFMFA+QM2WVOJcTJH3z901V/bQ790pQ7++CXwWyyI77Ck+tV004Inn3YeKWOuiGIKx+e+905Q39CUzuwk6DQhaN3Eq45pBdoJ+dEdEs6x+nhmKyz5v0pUku0sCnF49Qoseuy9k56A5AGENZlx0VW3HB7a76ro0bJD3J/kRTzBmwq4VzSuwJ67dnnAVE1k7k1Ah8ZKZa+aDd5B4i35mY/WLurzumPGW5JqHgwdgC6Cw+6gvp6I9hTRlJ5SjfZ+mLALsgoDuGyEazuPpeFb9WkcTass0UENLopDTVvr7qu3nmINzOq5THWukaen2lENL2cPA7C4=